allowed-duplicate-crates = [
  "base64",
  "bit-set",
  "bit-vec",
  "bitflags",
  "core-foundation",
  "event-listener",
  "fixedbitset",
  "hashbrown",
  "ndk",
  "ndk-sys",
  "redox_syscall",
  "regex-automata",
  "regex-syntax",
  "ttf-parser",
  "windows",
  "windows-core",
  "windows-implement",
  "windows-interface",
  "windows-result",
  "windows-strings",
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc",
]
